In [261]:
import pandas as pd

In [262]:
df1 = pd.read_csv("Cleaned_dataset.csv")

In [263]:
df1.head()

,Date_of_journey,Journey_day,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare
0,2023-01-16,Monday,SpiceJet,SG-8169,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335
1,2023-01-16,Monday,Indigo,6E-2519,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899
2,2023-01-16,Monday,GO FIRST,G8-354,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801
3,2023-01-16,Monday,SpiceJet,SG-8709,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794
4,2023-01-16,Monday,Air India,AI-805,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955

In [264]:
print(df1.columns)

Index(['Date_of_journey', 'Journey_day', 'Airline', 'Flight_code', 'Class',
       'Source', 'Departure', 'Total_stops', 'Arrival', 'Destination',
       'Duration_in_hours', 'Days_left', 'Fare'],
      dtype='str')

In [265]:
df1.shape

(452088, 13)

In [266]:
df2 = pd.read_csv("Scraped_dataset.csv")

In [267]:
df2.head()

,Date of Booking,Date of Journey,Airline-Class,Departure Time,Arrival Time,Duration,Total Stops,Price
0,15/01/2023,16/01/2023,SpiceJet \nSG-8169\nECONOMY,20:00\nDelhi,22:05\nMumbai,02h 05m,non-stop,"5,335"
1,15/01/2023,16/01/2023,Indigo \n6E-2519\nECONOMY,23:00\nDelhi,01:20\nMumbai,02h 20m,non-stop,"5,899"
2,15/01/2023,16/01/2023,GO FIRST \nG8- 354\nECONOMY,22:30\nDelhi,00:40\nMumbai,02h 10m,non-stop,"5,801"
3,15/01/2023,16/01/2023,SpiceJet \nSG-8709\nECONOMY,18:50\nDelhi,20:55\nMumbai,02h 05m,non-stop,"5,794"
4,15/01/2023,16/01/2023,Air India \nAI-805\nECONOMY,20:00\nDelhi,22:10\nMumbai,02h 10m,non-stop,"5,955"

In [268]:
df = df1

In [269]:
df

,Date_of_journey,Journey_day,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare
0,2023-01-16,Monday,SpiceJet,SG-8169,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335
1,2023-01-16,Monday,Indigo,6E-2519,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899
2,2023-01-16,Monday,GO FIRST,G8-354,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801
3,2023-01-16,Monday,SpiceJet,SG-8709,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794
4,2023-01-16,Monday,Air India,AI-805,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,Monday,Vistara,UK-926,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,13.0833,50,65028
452084,2023-03-06,Monday,Vistara,UK-918,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254
452085,2023-03-06,Monday,Vistara,UK-918,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254
452086,2023-03-06,Monday,Vistara,UK-946,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980
452087,2023-03-06,Monday,Vistara,UK-946,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980

In [270]:
df["Journey_day"].unique()

<StringArray>
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
Length: 7, dtype: str

In [271]:
df = pd.get_dummies(df, columns=['Journey_day'])

In [272]:
df

,Date_of_journey,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday
0,2023-01-16,SpiceJet,SG-8169,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,False,True,False,False,False,False,False
1,2023-01-16,Indigo,6E-2519,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,False,True,False,False,False,False,False
2,2023-01-16,GO FIRST,G8-354,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,False,True,False,False,False,False,False
3,2023-01-16,SpiceJet,SG-8709,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,False,True,False,False,False,False,False
4,2023-01-16,Air India,AI-805,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,Vistara,UK-926,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,13.0833,50,65028,False,True,False,False,False,False,False
452084,2023-03-06,Vistara,UK-918,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False
452085,2023-03-06,Vistara,UK-918,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False
452086,2023-03-06,Vistara,UK-946,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False
452087,2023-03-06,Vistara,UK-946,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False

In [273]:
df["Airline"].unique()

<StringArray>
[   'SpiceJet',      'Indigo',    'GO FIRST',   'Air India',     'AirAsia',
     'Vistara',    'AkasaAir', 'AllianceAir',     'StarAir']
Length: 9, dtype: str

In [274]:
df = pd.get_dummies(df, columns=["Airline"])

In [275]:
df

,Date_of_journey,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara
0,2023-01-16,SG-8169,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,2023-01-16,6E-2519,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,2023-01-16,G8-354,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,2023-01-16,SG-8709,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,2023-01-16,AI-805,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,UK-926,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,13.0833,50,65028,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452084,2023-03-06,UK-918,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452085,2023-03-06,UK-918,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452086,2023-03-06,UK-946,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452087,2023-03-06,UK-946,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [276]:
df["Flight_code"].unique()

<StringArray>
['SG-8169', '6E-2519',  'G8-354', 'SG-8709',  'AI-805',  'AI-605',  'AI-814',
  'G8-330', 'SG-2976',  'G8-346',
 ...
  '6E-117',  'SG-869', '6E-6556',  '6E-966',  '6E-261',  'SG-491',  '6E-921',
 '6E-6493', '6E-7073',  '6E-348']
Length: 1405, dtype: str

In [277]:
df.drop(["Flight_code"], axis=1, inplace=True)

In [278]:
df

,Date_of_journey,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara
0,2023-01-16,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,2023-01-16,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,2023-01-16,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,2023-01-16,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,2023-01-16,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,13.0833,50,65028,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452084,2023-03-06,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452085,2023-03-06,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452086,2023-03-06,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452087,2023-03-06,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [279]:
df["Class"].unique()

<StringArray>
['Economy', 'Premium Economy', 'Business', 'First']
Length: 4, dtype: str

In [280]:
df["Class"] = df["Class"].map({
    "Economy": 0,
    "Premium Economy" : 1,
    "Business": 2,
    "First": 3,
})

In [281]:
df

,Date_of_journey,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara
0,2023-01-16,0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,2023-01-16,0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,2023-01-16,0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,2023-01-16,0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,2023-01-16,0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,13.0833,50,65028,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452084,2023-03-06,2,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452085,2023-03-06,2,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452086,2023-03-06,2,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452087,2023-03-06,2,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [282]:
pd.set_option('display.max_columns', None)

In [283]:
df

,Date_of_journey,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara
0,2023-01-16,0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,2023-01-16,0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,2023-01-16,0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,2023-01-16,0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,2023-01-16,0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,13.0833,50,65028,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452084,2023-03-06,2,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452085,2023-03-06,2,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452086,2023-03-06,2,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
452087,2023-03-06,2,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [284]:
df["Source"].unique()

<StringArray>
['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Kolkata', 'Chennai',
 'Ahmedabad']
Length: 7, dtype: str

In [285]:
df = pd.get_dummies(df, columns = ["Source"])

In [286]:
df

,Date_of_journey,Class,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai
0,2023-01-16,0,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False
1,2023-01-16,0,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False
2,2023-01-16,0,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
3,2023-01-16,0,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False
4,2023-01-16,0,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,6 AM - 12 PM,1-stop,After 6 PM,Chennai,13.0833,50,65028,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False
452084,2023-03-06,2,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False
452085,2023-03-06,2,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False
452086,2023-03-06,2,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False
452087,2023-03-06,2,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False

In [287]:
df = pd.get_dummies(df, columns=["Destination"])

In [288]:
df

,Date_of_journey,Class,Departure,Total_stops,Arrival,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai
0,2023-01-16,0,After 6 PM,non-stop,After 6 PM,2.0833,1,5335,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
1,2023-01-16,0,After 6 PM,non-stop,Before 6 AM,2.3333,1,5899,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
2,2023-01-16,0,After 6 PM,non-stop,Before 6 AM,2.1667,1,5801,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
3,2023-01-16,0,After 6 PM,non-stop,After 6 PM,2.0833,1,5794,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
4,2023-01-16,0,After 6 PM,non-stop,After 6 PM,2.1667,1,5955,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,6 AM - 12 PM,1-stop,After 6 PM,13.0833,50,65028,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False
452084,2023-03-06,2,Before 6 AM,1-stop,12 PM - 6 PM,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False
452085,2023-03-06,2,Before 6 AM,1-stop,12 PM - 6 PM,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False
452086,2023-03-06,2,6 AM - 12 PM,1-stop,After 6 PM,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False
452087,2023-03-06,2,6 AM - 12 PM,1-stop,After 6 PM,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False

In [289]:
df["Total_stops"].unique()

<StringArray>
['non-stop', '1-stop', '2+-stop']
Length: 3, dtype: str

In [290]:
df["Total_stops"] = df["Total_stops"].map({
    "non-stop": 0,
    "1-stop":1,
    "2+-stop":2
})

In [291]:
df

,Date_of_journey,Class,Departure,Total_stops,Arrival,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai
0,2023-01-16,0,After 6 PM,0,After 6 PM,2.0833,1,5335,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
1,2023-01-16,0,After 6 PM,0,Before 6 AM,2.3333,1,5899,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
2,2023-01-16,0,After 6 PM,0,Before 6 AM,2.1667,1,5801,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
3,2023-01-16,0,After 6 PM,0,After 6 PM,2.0833,1,5794,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
4,2023-01-16,0,After 6 PM,0,After 6 PM,2.1667,1,5955,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,6 AM - 12 PM,1,After 6 PM,13.0833,50,65028,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False
452084,2023-03-06,2,Before 6 AM,1,12 PM - 6 PM,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False
452085,2023-03-06,2,Before 6 AM,1,12 PM - 6 PM,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False
452086,2023-03-06,2,6 AM - 12 PM,1,After 6 PM,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False
452087,2023-03-06,2,6 AM - 12 PM,1,After 6 PM,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False

In [292]:
df["Departure"].unique()

<StringArray>
['After 6 PM', 'Before 6 AM', '12 PM - 6 PM', '6 AM - 12 PM']
Length: 4, dtype: str

In [293]:
df = pd.get_dummies(df, columns=["Departure", "Arrival"])

In [294]:
df

,Date_of_journey,Class,Total_stops,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM
0,2023-01-16,0,0,2.0833,1,5335,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
1,2023-01-16,0,0,2.3333,1,5899,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
2,2023-01-16,0,0,2.1667,1,5801,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
3,2023-01-16,0,0,2.0833,1,5794,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
4,2023-01-16,0,0,2.1667,1,5955,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,1,13.0833,50,65028,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False
452084,2023-03-06,2,1,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
452085,2023-03-06,2,1,11.2500,50,69254,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
452086,2023-03-06,2,1,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False
452087,2023-03-06,2,1,11.1667,50,72980,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False

In [295]:
print(df.shape[1])

44

In [296]:
fare_max = df["Fare"].max()

In [297]:
fare_min = df["Fare"].min()

In [298]:
duration_min, duration_max = df["Duration_in_hours"].min(), df["Duration_in_hours"].max()

In [299]:
days_left_min, days_left_max = df["Days_left"].min(), df["Days_left"].max()

In [357]:
duration_min, duration_max, fare_min, fare_max, days_left_min, days_left_max

(np.float64(0.75),
 np.float64(43.5833),
 np.int64(1307),
 np.int64(143019),
 np.int64(1),
 np.int64(50))

In [300]:
df["Duration_in_hours"] = (df["Duration_in_hours"] - duration_min)/(duration_max - duration_min)

In [301]:
df["Fare"] = (df["Fare"] - fare_min)/(fare_max - fare_min)

In [302]:
df["Days_left"] = (df["Days_left"] - days_left_min)/(days_left_max - days_left_min)

In [303]:
df

,Date_of_journey,Class,Total_stops,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM
0,2023-01-16,0,0,0.031128,0.0,0.028424,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
1,2023-01-16,0,0,0.036964,0.0,0.032404,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
2,2023-01-16,0,0,0.033075,0.0,0.031712,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
3,2023-01-16,0,0,0.031128,0.0,0.031663,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
4,2023-01-16,0,0,0.033075,0.0,0.032799,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,1,0.287937,1.0,0.449651,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False
452084,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
452085,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
452086,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False
452087,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False

In [304]:
df

,Date_of_journey,Class,Total_stops,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM
0,2023-01-16,0,0,0.031128,0.0,0.028424,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
1,2023-01-16,0,0,0.036964,0.0,0.032404,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
2,2023-01-16,0,0,0.033075,0.0,0.031712,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
3,2023-01-16,0,0,0.031128,0.0,0.031663,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
4,2023-01-16,0,0,0.033075,0.0,0.032799,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,1,0.287937,1.0,0.449651,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False
452084,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
452085,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
452086,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False
452087,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False

In [305]:
df['Date_of_journey'] = pd.to_datetime(df['Date_of_journey'])

In [306]:
df

,Date_of_journey,Class,Total_stops,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM
0,2023-01-16,0,0,0.031128,0.0,0.028424,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
1,2023-01-16,0,0,0.036964,0.0,0.032404,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
2,2023-01-16,0,0,0.033075,0.0,0.031712,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
3,2023-01-16,0,0,0.031128,0.0,0.031663,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
4,2023-01-16,0,0,0.033075,0.0,0.032799,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,1,0.287937,1.0,0.449651,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False
452084,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
452085,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False
452086,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False
452087,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False

In [307]:
df['journey_day'] = df['Date_of_journey'].dt.day
df['journey_month'] = df['Date_of_journey'].dt.month
df['journey_weekday'] = df['Date_of_journey'].dt.weekday

In [308]:
df

,Date_of_journey,Class,Total_stops,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM,journey_day,journey_month,journey_weekday
0,2023-01-16,0,0,0.031128,0.0,0.028424,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0
1,2023-01-16,0,0,0.036964,0.0,0.032404,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0
2,2023-01-16,0,0,0.033075,0.0,0.031712,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0
3,2023-01-16,0,0,0.031128,0.0,0.031663,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0
4,2023-01-16,0,0,0.033075,0.0,0.032799,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,1,0.287937,1.0,0.449651,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0
452084,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0
452085,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0
452086,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0
452087,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0

In [309]:
df['is_weekend'] = df['journey_weekday'].isin([5, 6]).astype(int)

In [310]:
df

,Date_of_journey,Class,Total_stops,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM,journey_day,journey_month,journey_weekday,is_weekend
0,2023-01-16,0,0,0.031128,0.0,0.028424,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
1,2023-01-16,0,0,0.036964,0.0,0.032404,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0,0
2,2023-01-16,0,0,0.033075,0.0,0.031712,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0,0
3,2023-01-16,0,0,0.031128,0.0,0.031663,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
4,2023-01-16,0,0,0.033075,0.0,0.032799,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2023-03-06,2,1,0.287937,1.0,0.449651,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0
452084,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0,0
452085,2023-03-06,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0,0
452086,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0
452087,2023-03-06,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0

In [311]:
df["journey_weekday"].unique()

array([0, 1, 2, 3, 4, 5, 6], dtype=int32)

In [312]:
df.drop(columns=['Date_of_journey'], inplace=True)

In [313]:
df

,Class,Total_stops,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM,journey_day,journey_month,journey_weekday,is_weekend
0,0,0,0.031128,0.0,0.028424,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
1,0,0,0.036964,0.0,0.032404,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0,0
2,0,0,0.033075,0.0,0.031712,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0,0
3,0,0,0.031128,0.0,0.031663,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
4,0,0,0.033075,0.0,0.032799,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2,1,0.287937,1.0,0.449651,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0
452084,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0,0
452085,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0,0
452086,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0
452087,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0

In [314]:
df.dropna()

,Class,Total_stops,Duration_in_hours,Days_left,Fare,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM,journey_day,journey_month,journey_weekday,is_weekend
0,0,0,0.031128,0.0,0.028424,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
1,0,0,0.036964,0.0,0.032404,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0,0
2,0,0,0.033075,0.0,0.031712,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0,0
3,0,0,0.031128,0.0,0.031663,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
4,0,0,0.033075,0.0,0.032799,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2,1,0.287937,1.0,0.449651,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0
452084,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0,0
452085,2,1,0.245136,1.0,0.479472,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0,0
452086,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0
452087,2,1,0.243192,1.0,0.505765,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0,0

In [315]:
(df.columns)

Index(['Class', 'Total_stops', 'Duration_in_hours', 'Days_left', 'Fare',
       'Journey_day_Friday', 'Journey_day_Monday', 'Journey_day_Saturday',
       'Journey_day_Sunday', 'Journey_day_Thursday', 'Journey_day_Tuesday',
       'Journey_day_Wednesday', 'Airline_Air India', 'Airline_AirAsia',
       'Airline_AkasaAir', 'Airline_AllianceAir', 'Airline_GO FIRST',
       'Airline_Indigo', 'Airline_SpiceJet', 'Airline_StarAir',
       'Airline_Vistara', 'Source_Ahmedabad', 'Source_Bangalore',
       'Source_Chennai', 'Source_Delhi', 'Source_Hyderabad', 'Source_Kolkata',
       'Source_Mumbai', 'Destination_Ahmedabad', 'Destination_Bangalore',
       'Destination_Chennai', 'Destination_Delhi', 'Destination_Hyderabad',
       'Destination_Kolkata', 'Destination_Mumbai', 'Departure_12 PM - 6 PM',
       'Departure_6 AM - 12 PM', 'Departure_After 6 PM',
       'Departure_Before 6 AM', 'Arrival_12 PM - 6 PM', 'Arrival_6 AM - 12 PM',
       'Arrival_After 6 PM', 'Arrival_Before 6 AM', 'journey_day',
       'journey_month', 'journey_weekday', 'is_weekend'],
      dtype='str')

In [316]:
df.shape[1]

47

In [317]:
df_copy = df.copy()

In [318]:
y = df["Fare"]

In [319]:
x = df.drop("Fare", axis=1, inplace=True)
x = df.drop("journey_weekday", axis=1)

In [320]:
x

,Class,Total_stops,Duration_in_hours,Days_left,Journey_day_Friday,Journey_day_Monday,Journey_day_Saturday,Journey_day_Sunday,Journey_day_Thursday,Journey_day_Tuesday,Journey_day_Wednesday,Airline_Air India,Airline_AirAsia,Airline_AkasaAir,Airline_AllianceAir,Airline_GO FIRST,Airline_Indigo,Airline_SpiceJet,Airline_StarAir,Airline_Vistara,Source_Ahmedabad,Source_Bangalore,Source_Chennai,Source_Delhi,Source_Hyderabad,Source_Kolkata,Source_Mumbai,Destination_Ahmedabad,Destination_Bangalore,Destination_Chennai,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_Mumbai,Departure_12 PM - 6 PM,Departure_6 AM - 12 PM,Departure_After 6 PM,Departure_Before 6 AM,Arrival_12 PM - 6 PM,Arrival_6 AM - 12 PM,Arrival_After 6 PM,Arrival_Before 6 AM,journey_day,journey_month,is_weekend
0,0,0,0.031128,0.0,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0
1,0,0,0.036964,0.0,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0
2,0,0,0.033075,0.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,16,1,0
3,0,0,0.031128,0.0,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0
4,0,0,0.033075,0.0,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,16,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452083,2,1,0.287937,1.0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0
452084,2,1,0.245136,1.0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0
452085,2,1,0.245136,1.0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,6,3,0
452086,2,1,0.243192,1.0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0
452087,2,1,0.243192,1.0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,6,3,0

In [321]:
from sklearn.model_selection import train_test_split

In [322]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state=42)

In [323]:
from sklearn.linear_model import LinearRegression

In [324]:
lr = LinearRegression()

In [325]:
lr.fit(x_train, y_train)

LinearRegression()

In [326]:
print(f"Acccuracy on Linear Regression model is = {lr.score(x_test, y_test) * 100}%")

Acccuracy on Linear Regression model is = 77.1213758591401%

In [327]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(x_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [328]:
print(f"Acccuracy on Random Forest Regressor Model is = {rf.score(x_test, y_test) * 100}%")

Acccuracy on Random Forest Regressor Model is = 95.4790794910731%

In [329]:
print(rf.score(x_train, y_train))
print(rf.score(x_test, y_test))

0.9928283198498129
0.9547907949107309

In [330]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

xgb.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=-1, num_parallel_tree=None, ...)

In [331]:
y_pred = xgb.predict(x_test)

In [332]:
from sklearn.metrics import r2_score

print(r2_score(y_test, y_pred))

0.9557825526005603

In [333]:
print("Train Score:", xgb.score(x_train, y_train))
print("Test Score:", xgb.score(x_test, y_test))

Train Score: 0.9678897878737837
Test Score: 0.9557825526005603

In [334]:
importance_df = pd.DataFrame({
    'Feature': x.columns,
    'Importance': xgb.feature_importances_
})

print(
    importance_df.sort_values(
        by='Importance',
        ascending=False
    )
)

                   Feature  Importance
0                    Class    0.676306
11       Airline_Air India    0.025660
25          Source_Kolkata    0.019032
32     Destination_Kolkata    0.016941
2        Duration_in_hours    0.015647
23            Source_Delhi    0.013994
12         Airline_AirAsia    0.013865
30       Destination_Delhi    0.012325
27   Destination_Ahmedabad    0.012252
39    Arrival_6 AM - 12 PM    0.011725
41     Arrival_Before 6 AM    0.011558
20        Source_Ahmedabad    0.011001
33      Destination_Mumbai    0.010887
19         Airline_Vistara    0.010601
36    Departure_After 6 PM    0.009764
37   Departure_Before 6 AM    0.009338
16          Airline_Indigo    0.009329
3                Days_left    0.009165
26           Source_Mumbai    0.008488
1              Total_stops    0.007348
28   Destination_Bangalore    0.006998
40      Arrival_After 6 PM    0.006566
21        Source_Bangalore    0.006401
24        Source_Hyderabad    0.005998
35  Departure_6 AM - 12 PM    0.005645
29     Destination_Chennai    0.005560
22          Source_Chennai    0.005449
38    Arrival_12 PM - 6 PM    0.005263
31   Destination_Hyderabad    0.004885
34  Departure_12 PM - 6 PM    0.004591
15        Airline_GO FIRST    0.003155
44              is_weekend    0.003035
7       Journey_day_Sunday    0.002726
18         Airline_StarAir    0.002589
6     Journey_day_Saturday    0.002510
17        Airline_SpiceJet    0.002250
10   Journey_day_Wednesday    0.002056
9      Journey_day_Tuesday    0.001759
42             journey_day    0.001723
8     Journey_day_Thursday    0.001683
5       Journey_day_Monday    0.001638
4       Journey_day_Friday    0.001611
14     Airline_AllianceAir    0.000457
13        Airline_AkasaAir    0.000226
43           journey_month    0.000000

In [335]:
print(x.columns.tolist())

['Class', 'Total_stops', 'Duration_in_hours', 'Days_left', 'Journey_day_Friday', 'Journey_day_Monday', 'Journey_day_Saturday', 'Journey_day_Sunday', 'Journey_day_Thursday', 'Journey_day_Tuesday', 'Journey_day_Wednesday', 'Airline_Air India', 'Airline_AirAsia', 'Airline_AkasaAir', 'Airline_AllianceAir', 'Airline_GO FIRST', 'Airline_Indigo', 'Airline_SpiceJet', 'Airline_StarAir', 'Airline_Vistara', 'Source_Ahmedabad', 'Source_Bangalore', 'Source_Chennai', 'Source_Delhi', 'Source_Hyderabad', 'Source_Kolkata', 'Source_Mumbai', 'Destination_Ahmedabad', 'Destination_Bangalore', 'Destination_Chennai', 'Destination_Delhi', 'Destination_Hyderabad', 'Destination_Kolkata', 'Destination_Mumbai', 'Departure_12 PM - 6 PM', 'Departure_6 AM - 12 PM', 'Departure_After 6 PM', 'Departure_Before 6 AM', 'Arrival_12 PM - 6 PM', 'Arrival_6 AM - 12 PM', 'Arrival_After 6 PM', 'Arrival_Before 6 AM', 'journey_day', 'journey_month', 'is_weekend']

In [336]:
!pip install lightgbm

Collecting lightgbm
  Using cached lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from lightgbm) (2.4.4)
Requirement already satisfied: scipy in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from lightgbm) (1.17.1)
Using cached lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl (3.6 MB)
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [338]:

from lightgbm import LGBMRegressor

lgbm = LGBMRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=12,
    random_state=42
)

lgbm.fit(x_train, y_train)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022934 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 426
[LightGBM] [Info] Number of data points in the train set: 316461, number of used features: 45
[LightGBM] [Info] Start training from score 0.151844

LGBMRegressor(learning_rate=0.05, max_depth=12, n_estimators=500,
              random_state=42)

In [340]:
print("Train Score:", lgbm.score(x_train, y_train))
print("Test Score:", lgbm.score(x_test, y_test))

Train Score: 0.9338980015713767
Test Score: 0.9324762172994328

In [341]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from catboost) (3.10.9)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from catboost) (2.4.4)
Requirement already satisfied: pandas<4.0,>=0.24 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from catboost) (3.0.2)
Requirement already satisfied: scipy in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from catboost) (1.17.1)
Collecting plotly (from catboost)
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: six in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from matplotlib->catboost) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /home/punit/anaconda3/envs/ai/lib/python3.11/site-packages (from matplotlib->catboost) (3.3.2)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-2.21.0-py3-none-any.whl.metadata (16 kB)
Downloading catboost-1.2.10-cp311-cp311-manylinux2014_x86_64.whl (97.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.2/97.2 MB 3.6 MB/s  0:00:27 eta 0:00:01[36m0:00:01
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 4.3 MB/s  0:00:02a 0:00:01m eta 0:00:01
Downloading narwhals-2.21.0-py3-none-any.whl (451 kB)
Installing collected packages: narwhals, graphviz, plotly, catboost
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [catboost]━━ 3/4 [catboost]
Successfully installed catboost-1.2.10 graphviz-0.21 narwhals-2.21.0 plotly-6.7.0

In [342]:
from catboost import CatBoostRegressor

In [343]:
cat = CatBoostRegressor(
    iterations=500,
    learning_rate=0.05,
    depth=10,
    random_state=42,
    verbose=0
)

In [345]:
cat.fit(x_train, y_train)

CatBoostRegressor(depth=10, iterations=500, learning_rate=0.05, loss_function='RMSE', random_state=42, verbose=0)

In [347]:
print("Train Score:", cat.score(x_train, y_train))
print("Test Score:", cat.score(x_test, y_test))

Train Score: 0.9413098853330616
Test Score: 0.9386927461310185

In [353]:
from sklearn.neural_network import MLPRegressor

mlp = MLPRegressor(
    hidden_layer_sizes=(128, 64),
    max_iter=500,
    random_state=42
)

mlp.fit(x_train, y_train)

print("Train Score:", mlp.score(x_train, y_train))
print("Test Score:", mlp.score(x_test, y_test))

Train Score: 0.9188342071513965
Test Score: 0.9175980114654453

In [354]:
from sklearn.ensemble import ExtraTreesRegressor

et = ExtraTreesRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

et.fit(x_train, y_train)

print("Train Score:", et.score(x_train, y_train))
print("Test Score:", et.score(x_test, y_test))

Train Score: 0.9988156492087568
Test Score: 0.9367651525488002

In [355]:
"""
===========================================================
        AIRLINE FARE PREDICTION PROJECT REPORT
===========================================================

Project Objective:
------------------
The objective of this project was to build an AI-powered
airline fare prediction system capable of predicting flight
ticket prices using machine learning techniques on a large
real-world airline dataset.

Dataset Information:
--------------------
- Total Rows      : 452,000+
- Original Columns: 13
- Final Features  : 47
- Problem Type    : Regression

Data Preprocessing:
-------------------
The following preprocessing techniques were applied:

1. Handling categorical features using:
   - One-Hot Encoding:
       * Airline
       * Source
       * Destination
       * Departure Time
       * Arrival Time
       * Journey Weekday

   - Ordinal Encoding:
       * Class
       * Total Stops

2. Date Feature Engineering:
   Extracted:
   - journey_day
   - journey_month
   - journey_weekday
   - is_weekend

3. Duration conversion:
   Converted duration into numerical hours.

4. Removed redundant and unnecessary columns.

Machine Learning Models Used:
-----------------------------
1. Linear Regression
2. Random Forest Regressor
3. XGBoost Regressor
4. LightGBM Regressor
5. CatBoost Regressor
6. MLP Neural Network
7. Extra Trees Regressor

Model Performance:
------------------

1. Linear Regression
   - Accuracy (R² Score): ~77.12%

2. Random Forest Regressor
   - Train Score: 0.9928
   - Test Score : 0.9548

3. XGBoost Regressor
   - Train Score: 0.9679
   - Test Score : 0.9558

4. LightGBM Regressor
   - Train Score: 0.9339
   - Test Score : 0.9325

5. CatBoost Regressor
   - Train Score: 0.9413
   - Test Score : 0.9387

6. MLP Neural Network
   - Train Score: 0.9188
   - Test Score : 0.9176

7. Extra Trees Regressor
   - Train Score: 0.9988
   - Test Score : 0.9368

Final Model Selection:
----------------------
XGBoost Regressor was selected as the final model because:
- Highest test accuracy
- Strong generalization
- Low overfitting
- Excellent handling of nonlinear relationships

Key Insights:
--------------
- Flight Class was the most important feature.
- Airline, route, duration, and timing significantly
  affected fare prices.
- Tree boosting models outperformed linear models and
  neural networks on structured tabular data.

Challenges Faced:
-----------------
- Handling categorical data efficiently
- Preventing overfitting
- Detecting and fixing data leakage
- Managing large-scale preprocessing

Dataset:
---------
https://www.kaggle.com/datasets/yashdharme36/airfare-ml-predicting-flight-fares

Conclusion:
------------
This project successfully developed a high-performance
airline fare prediction system using advanced machine
learning techniques. The final XGBoost model achieved
approximately 95.58% R² accuracy with strong
generalization capability, making it suitable for
real-world airline pricing analytics applications.

===========================================================
"""

'\n===========================================================\n        AIRLINE FARE PREDICTION PROJECT REPORT\n===========================================================\n\nProject Objective:\n------------------\nThe objective of this project was to build an AI-powered\nairline fare prediction system capable of predicting flight\nticket prices using machine learning techniques on a large\nreal-world airline dataset.\n\nDataset Information:\n--------------------\n- Total Rows      : 452,000+\n- Original Columns: 13\n- Final Features  : 47\n- Problem Type    : Regression\n\nData Preprocessing:\n-------------------\nThe following preprocessing techniques were applied:\n\n1. Handling categorical features using:\n   - One-Hot Encoding:\n       * Airline\n       * Source\n       * Destination\n       * Departure Time\n       * Arrival Time\n       * Journey Weekday\n\n   - Ordinal Encoding:\n       * Class\n       * Total Stops\n\n2. Date Feature Engineering:\n   Extracted:\n   - journey_day\n   - journey_month\n   - journey_weekday\n   - is_weekend\n\n3. Duration conversion:\n   Converted duration into numerical hours.\n\n4. Removed redundant and unnecessary columns.\n\nMachine Learning Models Used:\n-----------------------------\n1. Linear Regression\n2. Random Forest Regressor\n3. XGBoost Regressor\n4. LightGBM Regressor\n5. CatBoost Regressor\n6. MLP Neural Network\n7. Extra Trees Regressor\n\nModel Performance:\n------------------\n\n1. Linear Regression\n   - Accuracy (R² Score): ~77.12%\n\n2. Random Forest Regressor\n   - Train Score: 0.9928\n   - Test Score : 0.9548\n\n3. XGBoost Regressor\n   - Train Score: 0.9679\n   - Test Score : 0.9558\n\n4. LightGBM Regressor\n   - Train Score: 0.9339\n   - Test Score : 0.9325\n\n5. CatBoost Regressor\n   - Train Score: 0.9413\n   - Test Score : 0.9387\n\n6. MLP Neural Network\n   - Train Score: 0.9188\n   - Test Score : 0.9176\n\n7. Extra Trees Regressor\n   - Train Score: 0.9988\n   - Test Score : 0.9368\n\nFinal Model Selection:\n----------------------\nXGBoost Regressor was selected as the final model because:\n- Highest test accuracy\n- Strong generalization\n- Low overfitting\n- Excellent handling of nonlinear relationships\n\nKey Insights:\n--------------\n- Flight Class was the most important feature.\n- Airline, route, duration, and timing significantly\n  affected fare prices.\n- Tree boosting models outperformed linear models and\n  neural networks on structured tabular data.\n\nChallenges Faced:\n-----------------\n- Handling categorical data efficiently\n- Preventing overfitting\n- Detecting and fixing data leakage\n- Managing large-scale preprocessing\n\nConclusion:\n------------\nThis project successfully developed a high-performance\nairline fare prediction system using advanced machine\nlearning techniques. The final XGBoost model achieved\napproximately 95.58% R² accuracy with strong\ngeneralization capability, making it suitable for\nreal-world airline pricing analytics applications.\n\n===========================================================\n'

In [366]:
# =========================================================
#         COMPLETE FLIGHT FARE PREDICTION SYSTEM
# =========================================================

import pandas as pd

# =========================================================
# MIN-MAX SCALING VALUES
# =========================================================

fare_min = 1307
fare_max = 143019

# =========================================================
# USER INPUTS
# =========================================================

# -----------------------------
# ORDINAL FEATURES
# -----------------------------

flight_class = int(input(
    "Class (Economy=0, Premium Economy=1, Business=2, First=3): "
))

total_stops = int(input(
    "Total Stops (non-stop=0, 1-stop=1, 2+-stop=2): "
))

# -----------------------------
# NUMERICAL FEATURES
# -----------------------------

duration_hours = float(input(
    "Duration in Hours (0.75 - 43.58): "
))

days_left = int(input(
    "Days Left Before Journey (1 - 50): "
))

journey_day = int(input(
    "Journey Date (1 - 31): "
))

journey_month = int(input(
    "Journey Month (1 - 12): "
))

is_weekend = int(input(
    "Is Weekend? (0=No, 1=Yes): "
))

# -----------------------------
# AIRLINE
# -----------------------------

print("\nAirlines:")
print("1 = Air India")
print("2 = AirAsia")
print("3 = AkasaAir")
print("4 = AllianceAir")
print("5 = GO FIRST")
print("6 = Indigo")
print("7 = SpiceJet")
print("8 = StarAir")
print("9 = Vistara")

airline = int(input("Choose Airline Number: "))

# -----------------------------
# SOURCE
# -----------------------------

print("\nSource Cities:")
print("1 = Ahmedabad")
print("2 = Bangalore")
print("3 = Chennai")
print("4 = Delhi")
print("5 = Hyderabad")
print("6 = Kolkata")
print("7 = Mumbai")

source = int(input("Choose Source City Number: "))

# -----------------------------
# DESTINATION
# -----------------------------

print("\nDestination Cities:")
print("1 = Ahmedabad")
print("2 = Bangalore")
print("3 = Chennai")
print("4 = Delhi")
print("5 = Hyderabad")
print("6 = Kolkata")
print("7 = Mumbai")

destination = int(input("Choose Destination City Number: "))

# -----------------------------
# DEPARTURE TIME
# -----------------------------

print("\nDeparture Time:")
print("1 = Before 6 AM")
print("2 = 6 AM - 12 PM")
print("3 = 12 PM - 6 PM")
print("4 = After 6 PM")

departure = int(input("Choose Departure Time Number: "))

# -----------------------------
# ARRIVAL TIME
# -----------------------------

print("\nArrival Time:")
print("1 = Before 6 AM")
print("2 = 6 AM - 12 PM")
print("3 = 12 PM - 6 PM")
print("4 = After 6 PM")

arrival = int(input("Choose Arrival Time Number: "))

# =========================================================
# CREATE INPUT DATAFRAME
# =========================================================

input_data = pd.DataFrame([{

    # Numerical / Ordinal
    "Class": flight_class,
    "Total_stops": total_stops,
    "Duration_in_hours": duration_hours,
    "Days_left": days_left,

    # Journey Days
    "Journey_day_Friday": 0,
    "Journey_day_Monday": 0,
    "Journey_day_Saturday": 0,
    "Journey_day_Sunday": 0,
    "Journey_day_Thursday": 0,
    "Journey_day_Tuesday": 0,
    "Journey_day_Wednesday": 0,

    # Airlines
    "Airline_Air India": 1 if airline == 1 else 0,
    "Airline_AirAsia": 1 if airline == 2 else 0,
    "Airline_AkasaAir": 1 if airline == 3 else 0,
    "Airline_AllianceAir": 1 if airline == 4 else 0,
    "Airline_GO FIRST": 1 if airline == 5 else 0,
    "Airline_Indigo": 1 if airline == 6 else 0,
    "Airline_SpiceJet": 1 if airline == 7 else 0,
    "Airline_StarAir": 1 if airline == 8 else 0,
    "Airline_Vistara": 1 if airline == 9 else 0,

    # Source
    "Source_Ahmedabad": 1 if source == 1 else 0,
    "Source_Bangalore": 1 if source == 2 else 0,
    "Source_Chennai": 1 if source == 3 else 0,
    "Source_Delhi": 1 if source == 4 else 0,
    "Source_Hyderabad": 1 if source == 5 else 0,
    "Source_Kolkata": 1 if source == 6 else 0,
    "Source_Mumbai": 1 if source == 7 else 0,

    # Destination
    "Destination_Ahmedabad": 1 if destination == 1 else 0,
    "Destination_Bangalore": 1 if destination == 2 else 0,
    "Destination_Chennai": 1 if destination == 3 else 0,
    "Destination_Delhi": 1 if destination == 4 else 0,
    "Destination_Hyderabad": 1 if destination == 5 else 0,
    "Destination_Kolkata": 1 if destination == 6 else 0,
    "Destination_Mumbai": 1 if destination == 7 else 0,

    # Departure
    "Departure_12 PM - 6 PM": 1 if departure == 3 else 0,
    "Departure_6 AM - 12 PM": 1 if departure == 2 else 0,
    "Departure_After 6 PM": 1 if departure == 4 else 0,
    "Departure_Before 6 AM": 1 if departure == 1 else 0,

    # Arrival
    "Arrival_12 PM - 6 PM": 1 if arrival == 3 else 0,
    "Arrival_6 AM - 12 PM": 1 if arrival == 2 else 0,
    "Arrival_After 6 PM": 1 if arrival == 4 else 0,
    "Arrival_Before 6 AM": 1 if arrival == 1 else 0,

    # Additional Features
    "journey_day": journey_day,
    "journey_month": journey_month,
    "is_weekend": is_weekend
}])

# =========================================================
# MATCH TRAINING COLUMN ORDER
# =========================================================

input_data = input_data[x.columns]

# =========================================================
# PREDICT SCALED VALUE
# =========================================================

scaled_prediction = xgb.predict(input_data)[0]

# =========================================================
# MANUAL INVERSE MIN-MAX SCALING
# =========================================================

actual_fare = (
    scaled_prediction * (fare_max - fare_min)
) + fare_min

# =========================================================
# OUTPUT
# =========================================================

print("\n==========================================")
print("Predicted Flight Fare = ₹", round(actual_fare, 2))
print("==========================================")

Class (Economy=0, Premium Economy=1, Business=2, First=3):  3
Total Stops (non-stop=0, 1-stop=1, 2+-stop=2):  0
Duration in Hours (0.75 - 43.58):  12
Days Left Before Journey (1 - 50):  1
Journey Date (1 - 31):  30
Journey Month (1 - 12):  12
Is Weekend? (0=No, 1=Yes):  1

Airlines:
1 = Air India
2 = AirAsia
3 = AkasaAir
4 = AllianceAir
5 = GO FIRST
6 = Indigo
7 = SpiceJet
8 = StarAir
9 = Vistara

Choose Airline Number:  1

Source Cities:
1 = Ahmedabad
2 = Bangalore
3 = Chennai
4 = Delhi
5 = Hyderabad
6 = Kolkata
7 = Mumbai

Choose Source City Number:  4

Destination Cities:
1 = Ahmedabad
2 = Bangalore
3 = Chennai
4 = Delhi
5 = Hyderabad
6 = Kolkata
7 = Mumbai

Choose Destination City Number:  6

Departure Time:
1 = Before 6 AM
2 = 6 AM - 12 PM
3 = 12 PM - 6 PM
4 = After 6 PM

Choose Departure Time Number:  4

Arrival Time:
1 = Before 6 AM
2 = 6 AM - 12 PM
3 = 12 PM - 6 PM
4 = After 6 PM

Choose Arrival Time Number:  1

==========================================
Predicted Flight Fare = ₹ 49151.57
==========================================

In [367]:
import joblib

In [368]:
joblib.dump(xgb, "flight_price_prediction_model.pkl")

['flight_price_prediction_model.pkl']